### PR TITLE
[bugfix] secretsdump.py and local hives

### PR DESCRIPTION
**Pull request by MrTchuss**
secretsdump.py is able again to retrieve secrets from locally stored
hives (secretsdump.py -sam SAM -security SECURITY -system SYSTEM LOCAL).

### CODE REVIEW

**Comment by asolino** [comment]
ja! Nice catch @MrTchuss!

Looks like nobody's using that functionality (most probably it mostly used for NTDS dump, which works).

I think there's an easier way of doing this w/o creating `_dump_*` methods. Let me check.

**Comment by asolino** [comment]
Take a look at my last commit, if it works on your side we can close this PR w/o merging.

Thanks again for spotting this @MrTchuss !

**Comment by MrTchuss** [comment]
It works on my side, so it's ok to close the PR.
Thanks for the fix @asolino !

**Comment by asolino** [comment]
Thanks to you for finding this @MrTchuss!

> For the record, this feature is really useful when getting physical access to a Windows machine with system privs. Creddump has not been updated for a long time, so afaik secretsdump.py is the only offline tool to retrieve MSCache and LSA secrets :) 

Ohh really?.. that is great to know mate :).. Glad impacket is useful.

cheers!

**Pull request closed without merging**
