### PR TITLE
 added simple paging support

### PR DESCRIPTION
**Pull request by kacpern**
This implements #190 plus does some extra stuff.

The only thing that is different from not using paging is that SearchResultReference were always at the very end of whatever search() returned (after SearchResultEntry). With paging SearchResultReference will show up after the first page in results. It probably makes no difference, but this can be fixed as commented [here](https://github.com/CoreSecurity/impacket/pull/193/files#diff-f9bdf90057454cf2c4047d1d69e613beR356) if we want to.

without paging:
```
impacket.ldap.ldapasn1.SearchResultEntry
...
impacket.ldap.ldapasn1.SearchResultEntry
impacket.ldap.ldapasn1.SearchResultReference
impacket.ldap.ldapasn1.SearchResultReference
impacket.ldap.ldapasn1.SearchResultReference
```
page size = 1:
```
impacket.ldap.ldapasn1.SearchResultEntry
impacket.ldap.ldapasn1.SearchResultReference
impacket.ldap.ldapasn1.SearchResultReference
impacket.ldap.ldapasn1.SearchResultReference
impacket.ldap.ldapasn1.SearchResultEntry
...
impacket.ldap.ldapasn1.SearchResultEntry
```

I've removed manualFilter in the end as the parsing algorithm should handle all filters now. To transition just use a string filter in the searchFilter attribute.

This is how to use the new paging functionality:
```python
from impacket.ldap.ldap import LDAPConnection
from impacket.ldap.ldapasn1 import SimplePagedResultsControl

conn = LDAPConnection(url, baseDN)
conn.login(username, password)

sc = SimplePagedResultsControl(True, 5)  # defaults are (criticality=False, size=1000, cookie='')
resp = conn.search(searchFilter='(&(objectCategory=person)(objectClass=user))', attributes=['cn'], sizeLimit=10, esearchControls=[sc])

for item in resp:
    print item.prettyPrint()
```

Please test.

Thanks to @the-useless-one for starting this [here](https://github.com/CoreSecurity/impacket/commit/daaa39f982c83f6ebe292291b08dc1351016f5a1).

### CODE REVIEW

**Comment by kacpern** [comment]
Reading more on the controls I think the control handling code should be moved lower into the recv() method. I will look into it.

**Comment by kacpern** [comment]
This is good to merge imho. Thoughts?

**Comment by the-useless-one** [comment]
Awesome, thanks @kacpern, I'll give it a go soon!

**Comment by asolino** [comment]
This looks great to merge @kacpern.. just merged.. Thanks a lot for your contributions!.. I hope this is not the last one :)

**Pull request merged**
