### PR TITLE
Add support for smb_com_nt_trasact request and nt_transact_query_security_desc.

### PR DESCRIPTION
**Pull request by contactr2m**
SMB_COM_NT_TRANSACT request and NT_TRANSACT_QUERY_SECURITY_DESC.

### CODE REVIEW

**Comment by contactr2m** [comment]
I have tested it and it works.. 

*-bash*mani@Macintosh-83~/impacket:[master !] python
Python 2.7.12 (default, Oct 18 2016, 22:06:54)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
>>> from impacket.smbconnection import SMBConnection, smb
>>> c =  SMBConnection(remoteHost='10.1.29.12', remoteName='10.1.29.12', preferredDialect=smb.SMB_DIALECT)
>>> c.login('user1', 'password1', 'dev')
>>> c.connectTree('rohit2')
1
>>> from impacket.smb3structs import *
>>> fid = c.openFile(1, 'test3', desiredAccess=GENERIC_READ)
>>> smb1 = c.getSMBServer()
>>> smb1.query_sec_info(1, fid)
'\x01\x00\x04\x80\x14\x00\x00\x000\x00\x00\x00\x00\x00\x00\x00L\x00\x00\x00\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\x852\xa5UU\x9d\xf7l\x07\x82\xc7FW\x04\x00\x00\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\x852\xa5UU\x9d\xf7l\x07\x82\xc7F\x01\x02\x00\x00\x02\x00\x1c\x00\x01\x00\x00\x00\x00\x10\x14\x00\xff\x01\x1f\x00\x01\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00'

```

**Comment by contactr2m** [comment]
If you implement structure for SecurityDescriptor then you get this with same buffer that we received in previous request.

```
SecurityDescriptor(res).dump()
SecurityDescriptor
Revision: {1}
Sbz1: {0}
Control: {32772}
OffsetOwner: {20}
OffsetGroup: {48}
OffsetSacl: {0}
OffsetDacl: {76}
Owner: {'S-1-5-21-1436889733-1828166997-1187480071-1111'}
Group: {'S-1-5-21-1436889733-1828166997-1187480071-513'}
Sacl: {''}
Dacl:{
    AclRevision: {2}
    Sbz1: {0}
    AclSize: {28}
    AceCount: {1}
    Sbz2: {0}
    ACE0:{
        Header:{
            AceType: {0}
            AceFlags: {16}
        }
        AceSize: {20}
        Mask: {2032127}
        SID: {'S-1-1-0'}
    }
}

```

I will also add code for SecurityDescriptor structure but it needs SID, ACL, ACE too. Its going to be a big PR.. 
Can you please check this first then let me know how to split next PR.. Dont want it to be too big. 

Thanks,
Cheers..
Mani

**Comment by asolino** [comment]
Thanks for the PR @contactr2m! Just landed it.

Indeed you will need to code some structures :).. Looks like you're used to it already. I had to do the same structures in its RPC format. You can check them [here](https://github.com/CoreSecurity/impacket/blob/master/impacket/dcerpc/v5/dtypes.py#L489). Might be of help.

**Comment by contactr2m** [comment]
Thank you for accepting it, i could not find better way to include it in test as there is no structure available yet.  
I have not added structure part because set acl stuff is not yet implemented on my side. 
Just want to make sure same structure will work for that too. I do not use NDR pointer so just curios.
I have separate classes for SID , ACL, ACE.

**Comment by asolino** [comment]
> Just want to make sure same structure will work for that too. I do not use NDR pointer so just curios.
I have separate classes for SID , ACL, ACE.

They won't. Those are RPC representation of those structures (that's why NDR is involved).

**Comment by contactr2m** [comment]
Ok cool, may be i will see if my existing structures works for applying acls. if that does then i will create new PR. Thank you again !

**Comment by contactr2m** [comment]
Hi @oblalex, 

1. I did implemented all structures required to get acl but i faced problems when i tried to set some security information. I'm still working on it on low  priority. Thanks for pointing out [samba code](http://mrs.suzu841.com/dox/samba_doxygen/rpc__secdes_8h-source.html)

```
class SecurityDescriptor(Structure):
    debug = 0
    structure = (
        ('Revision', '<B=0'),
        ('Sbz1', '<B=0'),
        ('Control', '<H=0'),
        ('OffsetOwner', '<L=0'),
        ('OffsetGroup', '<L=0'),
        ('OffsetSacl', '<L=0'),
        ('OffsetDacl', '<L=0'),
        ('Owner', ':'),
        ('Group', ':'),
        ('Sacl', ':'),
        ('Dacl', ':'),
    )

```
You can start with this...  

2. Yes you can resolve SIDs into names. [Check](https://github.com/CoreSecurity/impacket/blob/c049506e43ffa4c76dca7c676822ada7182f8288/impacket/dcerpc/v5/lsat.py#L469) lsat.hLsarLookupSids2() method in lsat.py You can query your AD server to get the names of users.
3. I tried to keep parameters same for both smb1 and smb2. [check this](https://github.com/CoreSecurity/impacket/blob/master/impacket/smb3.py#L1292)
Those constants are already defined [here:](https://github.com/CoreSecurity/impacket/blob/c049506e43ffa4c76dca7c676822ada7182f8288/impacket/smb3structs.py#L404)

**Comment by oblalex** [comment]
@contactr2m thanks for quick answer, that really helped! :+1:

**Comment by oblalex** [comment]
BTW, `impacket.dcerpc.v5.dtypes`  module already contains `SECURITY_DESCRIPTOR`.

**Comment by contactr2m** [comment]
@oblalex thats RPC representation, bit different.

**Comment by oblalex** [comment]
Yeah, I've noticed, thanks :)

**Pull request merged**
