### PR TITLE
added extensibleMatch string filter parsing

### PR DESCRIPTION
**Pull request by kacpern**
Must say you have motivated me to code this. I've checked with [here](https://github.com/CoreSecurity/impacket/blob/master/examples/GetUserSPNs.py#L218) and it seems to be working fine.

The 'not' filter is being built a bit differently in current code:
```
Filter:
 not=Not:
  notFilter=Filter:
   ...
```

vs old code:
```
Not:
 notFilter=Filter:
  ...
```

but it does not seem to make a difference. Testing would be appreciated.

Additionally, would be great if #190 is implemented ASAP. Really could use that functionality. I guess I could help.

### CODE REVIEW

**Comment by kacpern** [comment]
One more thing. Because I have actually changed [this line](https://github.com/CoreSecurity/impacket/pull/191/commits/e2379346a0ddc2a2217c7ef292c7d8dc2cda12e8#diff-f9bdf90057454cf2c4047d1d69e613beR330) I have probably broken some example code as now search() expects a string filter not a Filter() instance. Feel free to revert it back. Might as well move the parsing code to e.g. ldapasn1 module or other module. Up to you guys :)

**Comment by asolino** [comment]
This is great @kacpern!.. Just merged!..

Thanks for pointing our the `search()` API change.. I left it that way but also added a manualFilter parameter in case somebody wants to still use their own built filters.

Hey @the-useless-one have this in mind 'cause your project will break with this new PR. Either pass whatever you already have through the `manualFilter` parameter instead of the `searchFilter` or just use strings :)

Would love your help with #190 :)

**Comment by the-useless-one** [comment]
Oh my god, things are gonna be so much easier now :smiley:! Thanks @kacpern, I'll have to change my tool (it's gonna save so many lines of code).

As @asolino, any help on #190 would be much appreciated.

Cheers,

Y

**Comment by the-useless-one** [comment]
Hmm, I seem to have problem with this new PR :disappointed:.

I tried building my search filter with string, but I get an exception from the parsing code:

```
Search filter: (samAccountName=root)
Traceback (most recent call last):
  File "./pywerview.py", line 24, in <module>
    main()
  File "/home/yme/tools/pywerview/pywerview/cli/main.py", line 343, in main
    results = args.func(**parsed_args)
  File "/home/yme/tools/pywerview/pywerview/cli/helpers.py", line 31, in get_adobject
    queried_sam_account_name=queried_sam_account_name, ads_path=ads_path)
  File "/home/yme/tools/pywerview/pywerview/functions/requester.py", line 113, in wrapper
    return f(*args, **kwargs)
  File "/home/yme/tools/pywerview/pywerview/functions/net.py", line 60, in get_adobject
    return self._ldap_search(object_filter, adobj.ADObject)
  File "/home/yme/tools/pywerview/pywerview/functions/requester.py", line 82, in _ldap_search
    attributes=attributes)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 333, in search
    searchRequest['filter'] = self._parseFilter(searchFilter)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 402, in _parseFilter
    searchFilter = self._consumeCompositeFilter(filterList)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 422, in _consumeCompositeFilter
    return self._consumeSimpleFilter(filterList)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 471, in _consumeSimpleFilter
    return self._compileSimpleFilter(attribute, operator, value)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 534, in _compileSimpleFilter
    choice = EqualityMatch().setComponents(attribute, value)
AttributeError: EqualityMatch instance has no attribute 'setComponents'
```

I have the same problem when using the `GetUserSPNs.py` example:

```
$ git pull
Already up-to-date.
$ GetUserSPNs.py -dc-ip 192.168.47.132 -request uselessdomain.local/root
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

Password:
And instance has no attribute 'setComponents'
```

Any ideas?

**Comment by kacpern** [comment]
And() inherits from pyasn1.type.univ.SetOf() which in turn inherits from pyasn1.base.AbstractConstructedAsn1Item(). That last one has setComponents() implemented here: https://github.com/etingof/pyasn1/blob/master/pyasn1/type/base.py

You are also getting an AttributeError which lets me believe setComponents() was overwritten.

I'm on my phone now so I will check back when I get home, but it was working with my code.

**Comment by the-useless-one** [comment]
Hmm, this is weird, because I'm working with the Git repo version of impacket, and I didn't modify `GetUserSPNs.py`, so I don't see where the overwriting could be coming from...

Thanks for taking a look!

**Comment by kacpern** [comment]
```
"C:\Program Files (x86)\Python 2.7\python.exe" C:/Users/Kacper/Workspace/impacket/examples/GetUserSPNs.py -dc-ip {redacted} {domain}/{username}:{password}
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

ServicePrincipalName                                  Name      MemberOf                                                                                                    PasswordLastSet      LastLogon           
----------------------------------------------------  --------  ----------------------------------------------------------------------------------------------------------  -------------------  -------------------
MSSQLSvc/{redacted}                                   {red}     CN=View-Only Organization Management,OU=Microsoft Exchange Security Groups,DC=senseofsecurity,DC=com,DC=au  2007-10-13 10:43:17  2016-08-14 01:10:11 
MSSQLSvc/{redacted}                                   {red}     CN=View-Only Organization Management,OU=Microsoft Exchange Security Groups,DC=senseofsecurity,DC=com,DC=au  2007-10-13 10:43:17  2016-08-14 01:10:11 
HTTP/{redacted}                                       {red}     CN=Consultants,OU=Users & Groups,OU=PRD,OU=SYD,DC=senseofsecurity,DC=com,DC=au                              2011-07-27 16:19:08  2016-08-20 06:11:41 
HTTP/{redacted}                                       {red}      CN=Consultants,OU=Users & Groups,OU=PRD,OU=SYD,DC=senseofsecurity,DC=com,DC=au                            2011-07-27 16:19:08  2016-08-20 06:11:41 
HTTP/{redacted}                                       {red}     CN=Consultants,OU=Users & Groups,OU=PRD,OU=SYD,DC=senseofsecurity,DC=com,DC=au                              2011-07-27 16:19:08  2016-08-20 06:11:41 
HTTP/{redacted}                                       {red}    CN=Consultants,OU=Users & Groups,OU=PRD,OU=SYD,DC=senseofsecurity,DC=com,DC=au                          2011-07-27 16:19:08  2016-08-20 06:11:41 




Process finished with exit code 0
```

Look OK here.

**Pull request merged**
