### PR TITLE
Shellbrowserexec lateral movement example script

### PR DESCRIPTION
**Pull request by byt3bl33d3r**
Hey man!

This PR adds the shellbrowserexec lateral movement method (https://enigma0x3.net/2017/01/23/lateral-movement-via-dcom-round-2/) 

For some reason I can only get this to work on Windows 10, swapping the appropriate DCOM AppID strings seems to do nothing. I'm probably missing something obvious.

Cheers!

### CODE REVIEW

**Comment by asolino** [comment]
Thanks mate.. Just took a look at it.. Making it work with `ShellWindows` required just a tiny little step. Now that it works with both.. i'm wondering whether this is the right name for the script.. but can't come up with the right one :)

**Comment by asolino** [comment]
I'm actually thinking we could probably call this `dcomexec.py` and join it with MMC exec (and remove MMC exec), and let the user choose what object to instantiate for execution. Then, if more objects are discovered, we just add the functionality here. What say you?

**Comment by asolino** [comment]
Grrr... thought I could add to this pull request directly.. well.. there's a branch with your branch name here as well ;) https://github.com/CoreSecurity/impacket/compare/byt3bl33d3r-shellbrowserexec . Give a try and let me know what you think.

**Comment by byt3bl33d3r** [comment]
@asolino merging the two scripts is probably for the best! this way when we add even more DCOM lateral movement techniques we can have them all in one script 👍 

Just tried the script and works like a charm!!

**Comment by asolino** [comment]
great.. I'm closing this PR and merging https://github.com/CoreSecurity/impacket/tree/byt3bl33d3r-shellbrowserexec.
Thanks mate.

**Pull request closed without merging**
